config/routes.rb
Sc09forever::Application.routes.draw do
  get "home/index"
  resources :classmates

  root to: 'home#index'

end

app/models/classmate.rb
class Classmate < ActiveRecord::Base
	validates :name, :email, :qq, :description, :presence => true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, format: {with: VALID_EMAIL_REGEX} 
	validates :name, :length => { :in => 2..10 }
	validates :description, :length => { :maximum => 500 }
	has_attached_file :avatar, :styles => { :thumb => "300x200>" }, :default_url => "/images/:style/missing.png"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classmates_controller.rb
class ClassmatesController < ApplicationController
  before_action :set_classmate, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with :name => "songjiayang", :password => "liushan1314", :except => [:new,:create]
 

  # GET /classmates.json
  def index
    @classmates = Classmate.all
  end

  # GET /classmates/1
  # GET /classmates/1.json
  def show
  end

  # GET /classmates/new
  def new
    @classmate = Classmate.new
  end

  # GET /classmates/1/edit
  def edit
  end

  # POST /classmates
  # POST /classmates.json
  def create
    @classmate = Classmate.new(classmate_params)

    respond_to do |format|
      if @classmate.save
        format.html { redirect_to root_path, notice: 'Classmate was successfully created.' }
        format.json { render action: 'show', status: :created, location: @classmate }
      else
        format.html { render action: 'new' }
        format.json { render json: @classmate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classmates/1
  # PATCH/PUT /classmates/1.json
  def update
    respond_to do |format|
      if @classmate.update(classmate_params)
        format.html { redirect_to @classmate, notice: 'Classmate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @classmate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classmates/1
  # DELETE /classmates/1.json
  def destroy
    @classmate.destroy
    respond_to do |format|
      format.html { redirect_to classmates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classmate
      @classmate = Classmate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classmate_params
      params.require(:classmate).permit(:name, :email, :qq, :description, :avatar)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@classmates = Classmate.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classmates_helper.rb
module ClassmatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/classmates/_form.html.slim
= form_for @classmate, :html => { :class => "form-horizontal",:multipart => true } do |f|
  .control-group
    = f.label '名字', :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label '邮件', :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label 'qq号', :class => 'control-label'
    .controls
      = f.text_field :qq, :class => 'text_field'
  .control-group
    = f.label '祝福话语', :class => 'control-label'
    .controls
      = f.text_field :description, :class => 'text_field'
  .control-group
    = f.label '个性头像', :class=>'control-label'
    .controls
      = f.file_field :avatar, :class => 'text_field'
  .form-actions
    = f.submit '提交', :class => 'btn btn-primary'
    '
    = link_to t('.cancel', :default => t("helpers.links.cancel")), root_path, :class => 'btn'

app/views/classmates/edit.html.slim
- model_class = Classmate
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/classmates/index.html.slim
- model_class = Classmate
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:email)
      th= model_class.human_attribute_name(:qq)
      th= model_class.human_attribute_name(:description)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @classmates.each do |classmate|
      tr
        td= link_to classmate.id, classmate_path(classmate)
        td= classmate.name
        td= classmate.email
        td= classmate.qq
        td= classmate.description
        td= classmate.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_classmate_path(classmate), :class => 'btn btn-mini'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), classmate_path(classmate), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_classmate_path, :class => 'btn btn-primary'

app/views/classmates/new.html.slim
- model_class = Classmate
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/classmates/show.html.slim
- model_class = Classmate
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @classmate.name
p
  strong= model_class.human_attribute_name(:email) + ':'
  br
  = @classmate.email
p
  strong= model_class.human_attribute_name(:qq) + ':'
  br
  = @classmate.qq
p
  strong= model_class.human_attribute_name(:description) + ':'
  br
  = @classmate.description
p
  strong= model_class.human_attribute_name(:img_url) + ':'
  br
  = @classmate.img_url

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), classmates_path, :class => 'btn'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_classmate_path(@classmate), :class => 'btn'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), classmate_path(@classmate), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/home/index.html.slim
a.click-me href='/classmates/new' JOIN US
-@classmates.each do |classmate| 
		.item
				img src=classmate.avatar name=classmate.name description=classmate.description

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>这一年我们毕业</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
</body>
<% if controller_name=="home"%>
<script type="text/javascript">
	$("body").addClass("home");
</script>
<%end%>
</html>